### ISSUE TITLE
After installed im getting this issue, Please help me to fix this

### ISSUE THREAD

**Issue by sasiarjun** [demogorgorn/yii2-superfish-menu#1]
PHP Notice – yii\base\ErrorException

Undefined variable: items

**Comment by demogorgorn** [comment]
did you specified items options array?

**Comment by sasiarjun** [comment]
Yes I specified,  following same way I did,
echo \demogorgorn\superfish\Superfish::widget([
    'options' => [
        'class' => 'uk-float-right',
    ],
    'items' => [
        ['label' => 'First level menu item', 'url' => ['/site/index']],
        ['label' => 'First level menu item', 'url' => ['/site/preimushestva']],
        ['label' => 'First level m

**Comment by de-salvatierra** [comment]
Через композер устанавливается без этой правки

**Comment by demogorgorn** [comment]
сейчас поправим :)
